name: api

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "1010:80"
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./:/var/www/html

  mydb:
    image: mysql:8.0
    container_name: mydb
    ports:
      - "3308:3306"
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin:5.0
    container_name: phpmyadmin
    ports:
      - "8765:80"
    environment:
      - PMA_HOST=mydb
      - PMA_PORT=3306
    depends_on:
      - mydb

